// Generated by Wrangler by running `wrangler types`

interface Env {
  MCP_OBJECT: DurableObjectNamespace<import("./src/index.js").SimBriefMCP>;
  OAUTH_KV: KVNamespace;
  AI: Ai;
  CF_VERSION_METADATA: WorkerVersionMetadata;
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  COOKIE_ENCRYPTION_KEY: string;
  SIMBRIEF_API_KEY?: string;
  SENTRY_DSN?: string;
  ENVIRONMENT?: string;
}
